server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: front
          uri: http://localhost:8081
          predicates:
            - Path=/calls/**, 
        - id: taxi
          uri: http://localhost:8082
          predicates:
            - Path=/taxiCalls/**, /comments/**, 
        - id: point
          uri: http://localhost:8083
          predicates:
            - Path=/points/**, 
        - id: customer
          uri: http://localhost:8084
          predicates:
            - Path=, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: front
          uri: http://front:8080
          predicates:
            - Path=/calls/**, 
        - id: taxi
          uri: http://taxi:8080
          predicates:
            - Path=/taxiCalls/**, /comments/**, 
        - id: point
          uri: http://point:8080
          predicates:
            - Path=/points/**, 
        - id: customer
          uri: http://customer:8080
          predicates:
            - Path=, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
